name: Web

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web --release
      - run: git config user.name coder-Aayush
      - run: git config user.email bhattaraiaayush08@gmail.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "build web"
      - run: git push origin HEAD:web --force
